server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/knjiznica
    username: knjige
    password: knjige
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
